# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

# Blog Settings
theme_settings :
  title : Balpreet Singh
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Balpreet Singh Banga
    description : creator of Grape-Theme! Grape-Theme is my first jekyll theme and you can customize this theme easily.
    experience :
      - start : 01-08-2018
        end : Present
        experience : BCA
      
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
      - skill : Python
        value : 70
      - skill : C and C++
        value : 90
      - skill : JAVA
        value : 70 
  # Icons
  icons :
    email:  balpreet.bangz1999@gmail.com
    linkedin:  # Full URL 
    github: https://github.com/BALPREET1999
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook: https://www.facebook.com/balpreet.singh.5437
    instagram: https://www.instagram.com/bal._.preet

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
